### ISSUE TITLE
Filtering 

### ISSUE THREAD

**Issue by AnyxLeo** [unosquare/tubular-dotnet#9]
**Is your feature request related to a problem? Please describe.**
Some filters aren't working properly.
No matters which filter option are you selecting, the payload request didn't bring the correct information.
It seems to be the way the entity framework makes the query to the SQL engine.

**Additional context**
(https://stackoverflow.com/questions/48988623/queryablet-union-behaviour-in-efcore).

**Comment by geoperez** [comment]
Please remove the content related to the external project and explain the issue properly.

**Comment by geoperez** [comment]
@AnyxLeo can you restest this issue with EF Core 3.0?

**Comment by geoperez** [comment]
Status?!
